name: "Add current user as Assignees"
description: "Add current user as Assignees at Pull Request"

runs:
  using: "composite"
  steps:
    - run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{github.token}}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/${{github.repository}}/issues/${{github.event.number}}/assignees \
        -d '{"assignees":"${{github.actor}}"}'
      shell: bash
