name: Deploy Stack
description: "Run cdk deploy command. You can send stack-name property for deploy a specified Stack."

inputs:
  cdk-app-path:
    required: true
    description: 'Path from CDK APP.'
  stack-name:
    required: false
    description: 'Stack name to deploy.'
    default: ''
  custom-args:
    required: false
    description: 'Custom arguments: "Example: --all"'
    default: ''

runs:
  using: "composite"
  steps:
    - run: |
        sudo npm install -g aws-cdk
        cd ${{inputs.cdk-app-path}} && npm install
        cdk deploy ${{inputs.stack-name}} --require-approval never ${{inputs.custom-args}}
      shell: bash
