name: Build Lambda Function ARM64
description: |
  Build the package ready for upload to aws lambda function in ARM64 architecture.
  Inputs:
  - (Required) app-path: Path of main folder project.
  - (Required) root-module-name: Name of entry module app.
  - (Optional) requirements-file: Requirements file for pip install (default: requirements.txt).
  - (Optional) zip-file-name: Name for output-file.zip (default: lambda-package.zip).
author: nocour

inputs:
  app-path:
    required: true
    description: '(Required) Path of main folder project.'
  root-module-name:
    required: true
    description: '(Required) Name of entry module app.'
  requirements-file:
    required: false
    description: '(Optional) Requirements file for pip install (default: requirements.txt).'
    default: requirements.txt
  zip-file-name:
    required: false
    description: '(Optional) Name for output-file.zip (default: lambda-package.zip).'
    default: lambda-package.zip
  pip3-args:
    required: false
    description: '(Optional) custom arguments for pip3 install (default: --platform arm64).'
    default: --platform arm64

runs:
  using: 'composite'
  steps:
    - run: |
        pip3 install -r ${{inputs.requirements-file}} --only-binary=:all: --target temp-folder ${{inputs.pip3-args}}
        cp -r ${{inputs.app-path}} temp-folder/${{inputs.root-module-name}}
        cd temp-folder
        zip -r ../${{inputs.zip-file-name}} .
      shell: bash