name: 'Get github.email by github.actor'
description: 'Get email address by actor'

runs:
  using: 'composite'
  steps:
    - run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{github.token}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/users/${{github.actor}} -o data.json
          echo "GITHUB_EMAIL=$(jq -r '.email' data.json)" >> $GITHUB_ENV
      shell: bash