name: Update code to lambda function
description: Update code to lambda function by function-name
author: nocour

inputs:
  function-name:
    required: true
    description: 'Name of Lambda Function'
  zip-file-name:
    required: true
    description: 'Path of zip file with code.'

runs:
  using: "composite"
  steps:
    - run: |
        aws lambda update-function-code --function-name ${{inputs.function-name}} --zip-file fileb://${{inputs.zip-file-name}}
      shell: bash
