name: Update code of lambda function
description: Update code of lambda function by function-name

inputs:
  function-name:
    required: true
    description: 'Name of Lambda Function'
  zip-file:
    required: true
    description: 'Path of zip file with code.'

runs:
  using: "composite"
  steps:
    - run: |
        aws lambda update-function-code --function-name ${{inputs.function-name}} --zip-file ${{inputs.zip-file}}
      shell: bash
