name: Sync S3 Bucket
description: Sync files from local to S3 Bucket
author: nocour

inputs:
  s3-uri:
    required: true
    description: 'URI of S3 Bucket Folder s3://<bucket>/<folder>'
  local-folder:
    required: true
    description: 'Path to local folder'

runs:
  using: "composite"
  steps:
    - run: |
        aws s3 sync ${{inputs.local-folder}} ${{inputs.s3-uri}}
      shell: bash