name: "Add Services Team as Reviewers"
description: "Add Services Team as Reviewers at Pull Request"

runs:
  using: "composite"
  steps:
    - run: |
        original='["Halty-Maximo_pfghub","blanco-jorge_pfghub","navarro-andres-j_pfghub","aguilar-carlos_pfghub","diaz-francisca_pfghub"]'
        result=${original//"\"${{github.actor}}\""/""}
        result=${result//,,/,}
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{github.token}}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/${{github.repository}}/pulls/${{github.event.number}}/requested_reviewers \
        -d "{\"reviewers\":$result}"
      shell: bash
