on:
  workflow_call:
    inputs:
      project-path:
        required: true
        type: string
      zip-file-name:
        required: true
        type: string
      function-name:
        required: true
        type: string
      aws-access-key:
        required: true
        type: string
      aws-region:
        required: true
        type: string
      env-name:
        required: true
        type: string

    secrets:
      aws-secret-access-key:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - uses: nocour/github-actions/dotnet-tools/build-lambda@0.2.0
        with:
          project-path: ${{inputs.project-path}}
          zip-file-name: ${{inputs.zip-file-name}}

      - uses: actions/upload-artifact@v3
        with:
          name: publish-dotnet
          path: publish-dotnet/

  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    environment: ${{ inputs.env-name }}
    env:
      ENV: ${{ inputs.env-name }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ inputs.aws-access-key }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ inputs.aws-region }}

      - uses: nocour/github-actions/aws-tools/lambda/functions/update-code@0.2.0
        with:
          function-name: ${{inputs.function-name}}
          zip-file: fileb://publish-dotnet/${{inputs.zip-file-name}}
