on:
  workflow_call:
    inputs:
      aws-access-key:
        required: true
        type: string
      aws-region:
        required: true
        type: string
      env-name:
        required: true
        type: string
      app-path:
        required: true
        type: string
      bucket:
        required: true
        type: string
      build-args:
        required: false
        type: string
      distribution-id:
        required: false
        type: string

    secrets:
      aws-secret-access-key:
        required: true

jobs:
  build-sync:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env-name }}
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ inputs.aws-access-key }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ inputs.aws-region }}
      - name: Build & Sync
        run: |
          cd ${{inputs.app-path}}
          bun install
          bun run build ${{inputs.build-args}}
          cd dist
          aws s3 sync . ${{inputs.bucket}} --delete
      - name: Clean Cache
        if: ${{inputs.distribution-id}}
        run: aws cloudfront create-invalidation --distribution-id ${{vars.DISTRIBUTION_ID}} --paths /index.html